// NOTE: seriumium
module.exports.exec = require('./seriumium/exec')
module.exports.script = require('./seriumium/script')
// NOTE: moderations
module.exports.delete = require('./moderations/delete')
module.exports.sayd = require('./moderations/sayd')
// NOTE: gladsome
module.exports.choose = require('./gladsome/choose')
module.exports.note = require('./gladsome/note')
module.exports.probability = require('./gladsome/probability')
module.exports.ready = require('./gladsome/ready')
module.exports.rps = require('./gladsome/rps')
module.exports.say = require('./gladsome/say')
// NOTE: images
module.exports.avatar = require('./images/avatar')
module.exports.cat = require('./images/cat')
module.exports.dog = require('./images/dog')
module.exports.neko = require('./images/neko')
module.exports.shy = require('./images/shy')
// NOTE: about
module.exports.help = require('./about/help')
module.exports.ping = require('./about/ping')
module.exports.serverinfo = require('./about/serverinfo')
module.exports.userinfo = require('./about/userinfo')
// NOTE: wiki
module.exports.library = require('./wiki/library')
module.exports.namuwiki = require('./wiki/namuwiki')
// NOTE: functions
module.exports.search = require('./functions/search')
module.exports.hash = require('./functions/hash')
