module.exports.avatar = require('./avatar')
module.exports.cat = require('./cat')
module.exports.hug = require('./hug')
module.exports.kiss = require('./kiss')
module.exports.neko = require('./neko')
