module.exports = (prompts, _prompts) => {
  // NOTE: Administrations levels: it doesn't contains any translations or alias, options. Just leave options as 'undefined' not 'null'.
  prompts.set('exec', { worker: _prompts.exec, language: 'en' })
  prompts.set('script', { worker: _prompts.script, language: 'en' })
  // NOTE: Don't initialize 'say' and 'sayd' prompt twice
  prompts.set('avatar', { worker: _prompts.avatar, language: 'en' })
  prompts.set('cat', { worker: _prompts.cat, language: 'en' })
  prompts.set('choose', { worker: _prompts.choose, language: 'en' })
  prompts.set('delete', { worker: _prompts.delete, language: 'en' })
  prompts.set('dog', { worker: _prompts.dog, language: 'en' })
  prompts.set('help', { worker: _prompts.help, language: 'en' })
  prompts.set('library', { worker: _prompts.library, language: 'en' })
  prompts.set('namuwiki', { worker: _prompts.namuwiki, language: 'en' })
  prompts.set('neko', { worker: _prompts.neko, language: 'en' })
  prompts.set('ping', { worker: _prompts.ping, language: 'en' })
  prompts.set('probability', { worker: _prompts.probability, language: 'en' })
  prompts.set('ready', { worker: _prompts.ready, language: 'en' })
  prompts.set('rps', { worker: _prompts.rps, language: 'en' })
  prompts.set('say', { worker: _prompts.say, language: 'en' })
  prompts.set('sayd', { worker: _prompts.sayd, language: 'en' })
  prompts.set('search', { worker: _prompts.search, language: 'en' })
  prompts.set('shy', { worker: _prompts.shy, language: 'en' })
  prompts.set('serverinfo', { worker: _prompts.serverinfo, language: 'en' })
  prompts.set('userinfo', { worker: _prompts.userinfo, language: 'en' })
  prompts.set('note', { worker: _prompts.note, language: 'en' })

  // NOTE: Korean Language Package
  prompts.set('아바타', { worker: _prompts.avatar, language: 'ko' })
  prompts.set('고양이', { worker: _prompts.cat, language: 'ko' })
  prompts.set('선택', { worker: _prompts.choose, language: 'ko' })
  prompts.set('강아지', { worker: _prompts.dog, language: 'ko' })
  prompts.set('삭제', { worker: _prompts.delete, language: 'ko' })
  prompts.set('도움말', { worker: _prompts.help, language: 'ko' })
  prompts.set('라이브러리', { worker: _prompts.library, language: 'ko' })
  prompts.set('나무위키', { worker: _prompts.namuwiki, language: 'ko' })
  prompts.set('네코', { worker: _prompts.neko, language: 'ko' })
  prompts.set('질의', { worker: _prompts.ping, language: 'ko' })
  prompts.set('확률', { worker: _prompts.probability, language: 'ko' })
  prompts.set('준비', { worker: _prompts.ready, language: 'ko' })
  prompts.set('가위바위보', { worker: _prompts.rps, language: 'ko' })
  prompts.set('검색', { worker: _prompts.search, language: 'ko' })
  prompts.set('부끄러워', { worker: _prompts.shy, language: 'ko' })
  prompts.set('서버정보', { worker: _prompts.serverinfo, language: 'ko' })
  prompts.set('사용자정보', { worker: _prompts.userinfo, language: 'ko' })
  prompts.set('노트', { worker: _prompts.note, language: 'ko' })
}
