module.exports.configure = require('./configure')
module.exports.disable = require('./disable')
module.exports.enable = require('./enable')
module.exports.palette = require('./palette')
module.exports.plugin = require('./plugin')
